# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import signal_pb2 as signal__pb2


class SignalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBookTickers = channel.unary_unary(
                '/signal.Signal/GetBookTickers',
                request_serializer=signal__pb2.BookTickerReq.SerializeToString,
                response_deserializer=signal__pb2.BookTickerResp.FromString,
                )


class SignalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBookTickers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBookTickers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookTickers,
                    request_deserializer=signal__pb2.BookTickerReq.FromString,
                    response_serializer=signal__pb2.BookTickerResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'signal.Signal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Signal(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBookTickers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/signal.Signal/GetBookTickers',
            signal__pb2.BookTickerReq.SerializeToString,
            signal__pb2.BookTickerResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
