# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signal.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='signal.proto',
  package='signal',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csignal.proto\x12\x06signal\"B\n\rBookTickerReq\x12\"\n\x08\x65xchange\x18\x01 \x01(\x0e\x32\x10.signal.EXCHANGE\x12\r\n\x05pairs\x18\x02 \x03(\t\"\x86\x01\n\x0e\x42ookTickerResp\x12.\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32 .signal.BookTickerResp.DataEntry\x1a\x44\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.signal.PairBookTickers:\x02\x38\x01\"f\n\x0ePairBookTicker\x12\'\n\x0bmargin_type\x18\x01 \x01(\x0e\x32\x12.signal.MarginType\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x0b\n\x03\x62id\x18\x03 \x01(\x02\x12\x0b\n\x03\x61sk\x18\x04 \x01(\x02\":\n\x0fPairBookTickers\x12\'\n\x07tickers\x18\x01 \x03(\x0b\x32\x16.signal.PairBookTicker*8\n\nMarginType\x12\x08\n\x04SPOT\x10\x00\x12\x0f\n\x0bUSDT_MARGIN\x10\x01\x12\x0f\n\x0b\x43OIN_MARGIN\x10\x02*\x17\n\x08\x45XCHANGE\x12\x0b\n\x07\x42INANCE\x10\x00\x32K\n\x06Signal\x12\x41\n\x0eGetBookTickers\x12\x15.signal.BookTickerReq\x1a\x16.signal.BookTickerResp\"\x00\x62\x06proto3'
)

_MARGINTYPE = _descriptor.EnumDescriptor(
  name='MarginType',
  full_name='signal.MarginType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SPOT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='USDT_MARGIN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COIN_MARGIN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=393,
  serialized_end=449,
)
_sym_db.RegisterEnumDescriptor(_MARGINTYPE)

MarginType = enum_type_wrapper.EnumTypeWrapper(_MARGINTYPE)
_EXCHANGE = _descriptor.EnumDescriptor(
  name='EXCHANGE',
  full_name='signal.EXCHANGE',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BINANCE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=451,
  serialized_end=474,
)
_sym_db.RegisterEnumDescriptor(_EXCHANGE)

EXCHANGE = enum_type_wrapper.EnumTypeWrapper(_EXCHANGE)
SPOT = 0
USDT_MARGIN = 1
COIN_MARGIN = 2
BINANCE = 0



_BOOKTICKERREQ = _descriptor.Descriptor(
  name='BookTickerReq',
  full_name='signal.BookTickerReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchange', full_name='signal.BookTickerReq.exchange', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pairs', full_name='signal.BookTickerReq.pairs', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=90,
)


_BOOKTICKERRESP_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='signal.BookTickerResp.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='signal.BookTickerResp.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='signal.BookTickerResp.DataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=227,
)

_BOOKTICKERRESP = _descriptor.Descriptor(
  name='BookTickerResp',
  full_name='signal.BookTickerResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='signal.BookTickerResp.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BOOKTICKERRESP_DATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=227,
)


_PAIRBOOKTICKER = _descriptor.Descriptor(
  name='PairBookTicker',
  full_name='signal.PairBookTicker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='margin_type', full_name='signal.PairBookTicker.margin_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='signal.PairBookTicker.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bid', full_name='signal.PairBookTicker.bid', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ask', full_name='signal.PairBookTicker.ask', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=331,
)


_PAIRBOOKTICKERS = _descriptor.Descriptor(
  name='PairBookTickers',
  full_name='signal.PairBookTickers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tickers', full_name='signal.PairBookTickers.tickers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=391,
)

_BOOKTICKERREQ.fields_by_name['exchange'].enum_type = _EXCHANGE
_BOOKTICKERRESP_DATAENTRY.fields_by_name['value'].message_type = _PAIRBOOKTICKERS
_BOOKTICKERRESP_DATAENTRY.containing_type = _BOOKTICKERRESP
_BOOKTICKERRESP.fields_by_name['data'].message_type = _BOOKTICKERRESP_DATAENTRY
_PAIRBOOKTICKER.fields_by_name['margin_type'].enum_type = _MARGINTYPE
_PAIRBOOKTICKERS.fields_by_name['tickers'].message_type = _PAIRBOOKTICKER
DESCRIPTOR.message_types_by_name['BookTickerReq'] = _BOOKTICKERREQ
DESCRIPTOR.message_types_by_name['BookTickerResp'] = _BOOKTICKERRESP
DESCRIPTOR.message_types_by_name['PairBookTicker'] = _PAIRBOOKTICKER
DESCRIPTOR.message_types_by_name['PairBookTickers'] = _PAIRBOOKTICKERS
DESCRIPTOR.enum_types_by_name['MarginType'] = _MARGINTYPE
DESCRIPTOR.enum_types_by_name['EXCHANGE'] = _EXCHANGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BookTickerReq = _reflection.GeneratedProtocolMessageType('BookTickerReq', (_message.Message,), {
  'DESCRIPTOR' : _BOOKTICKERREQ,
  '__module__' : 'signal_pb2'
  # @@protoc_insertion_point(class_scope:signal.BookTickerReq)
  })
_sym_db.RegisterMessage(BookTickerReq)

BookTickerResp = _reflection.GeneratedProtocolMessageType('BookTickerResp', (_message.Message,), {

  'DataEntry' : _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), {
    'DESCRIPTOR' : _BOOKTICKERRESP_DATAENTRY,
    '__module__' : 'signal_pb2'
    # @@protoc_insertion_point(class_scope:signal.BookTickerResp.DataEntry)
    })
  ,
  'DESCRIPTOR' : _BOOKTICKERRESP,
  '__module__' : 'signal_pb2'
  # @@protoc_insertion_point(class_scope:signal.BookTickerResp)
  })
_sym_db.RegisterMessage(BookTickerResp)
_sym_db.RegisterMessage(BookTickerResp.DataEntry)

PairBookTicker = _reflection.GeneratedProtocolMessageType('PairBookTicker', (_message.Message,), {
  'DESCRIPTOR' : _PAIRBOOKTICKER,
  '__module__' : 'signal_pb2'
  # @@protoc_insertion_point(class_scope:signal.PairBookTicker)
  })
_sym_db.RegisterMessage(PairBookTicker)

PairBookTickers = _reflection.GeneratedProtocolMessageType('PairBookTickers', (_message.Message,), {
  'DESCRIPTOR' : _PAIRBOOKTICKERS,
  '__module__' : 'signal_pb2'
  # @@protoc_insertion_point(class_scope:signal.PairBookTickers)
  })
_sym_db.RegisterMessage(PairBookTickers)


_BOOKTICKERRESP_DATAENTRY._options = None

_SIGNAL = _descriptor.ServiceDescriptor(
  name='Signal',
  full_name='signal.Signal',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=476,
  serialized_end=551,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetBookTickers',
    full_name='signal.Signal.GetBookTickers',
    index=0,
    containing_service=None,
    input_type=_BOOKTICKERREQ,
    output_type=_BOOKTICKERRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIGNAL)

DESCRIPTOR.services_by_name['Signal'] = _SIGNAL

# @@protoc_insertion_point(module_scope)
